// <auto-generated />
using System;
using DesafioGlobo.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioGlobo.Infra.Data.Migrations
{
    [DbContext(typeof(ContextBase))]
    partial class ContextBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DesafioGlobo.Domain.Entities.TransferArchiveControl", b =>
                {
                    b.Property<Guid>("IdTransferArchiveControl")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CheckSum")
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("CreateDate");

                    b.Property<DateTime?>("DateSend");

                    b.Property<Guid?>("IdResponse");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<int>("TypeAction");

                    b.HasKey("IdTransferArchiveControl");

                    b.ToTable("TransferArchiveControl");
                });
#pragma warning restore 612, 618
        }
    }
}
